#Change to MySQL for mysql support#
#Change to SQLite for sqlite support#
Database: SQLite
mysql-database: 'jdbc:mysql://localhost:3306/minecraft'
mysql-user: 'root'
mysql-password: 'root'
#Change these if you want to load or create different databases#
#First load will create these databases#
mysql-table: banlist
mysql-table-ip: banlistip
#SQLite Information#
sqlite-dbname: banlist
#parameters#
auto-complete: true
#Max Warnings#
enableMaxWarn: false#
maxWarnings: 5
#ban,kick,ipban,perma,tempban,tempipban#
maxWarnResult: ban
#Used with Temporary actions#
maxWarnResulttime:
  amt: 5
  #sec,min,hour,day,week,month#
  mode: day
#Default labels#
defAdminName: 'server'
defReason: 'not sure'
#Extended ban time#
defExtTime:   
  amt: 5
  #sec,min,hour,day,week,month#
  mode: min
#Messages#
messages:
  banMsgFailed: '&4%victim% &7is already banned!'
  unbanMsg: '&7Successfully unbanned &4%victim%&7!'
  unbanMsgBroadcast: '&4%victim% &7was unbanned by &3%admin%&7!'
  unbanMsgFailed: '&4%victim% &7is already unbanned!'
  kickAllMsg: '%admin% kicked everyone. Reason: %reason%!'
  kickMsgVictim: 'You have been kicked by %admin%. Reason: %reason%!'
  kickMsgBroadcast: '&4%victim% &7was kicked by &3%admin%&7. Reason: &4%reason%!'
  kickMsgFailed: '&7Kick failed: &7%victim% &7isn''t online.'
  banMsgVictim: 'You have been banned by %admin%. Reason: %reason%!'
  banMsgBroadcast: '&4%victim% &7was banned by &3%admin%&7. Reason: &4%reason%!'
  permbanMsgVictim: 'You have been permabanned by %admin%. Reason: %reason%!'
  permbanMsgBroadcast: '&4%victim% &7has been permabanned by &3%admin%&7. Reason: &4%reason%!'
  tempbanMsgVictim: 'You have been temp. banned by %admin%. Reason: %reason%!'
  tempbanMsgBroadcast: '&4%victim% &7was temp. banned by &3%admin%&7. Reason: &4%reason%!'
  LoginTempban: '&7You are banned until &4%time%&7! Reason: &4%reason%!'
  LoginBan: '%admin% banned you from this server! Reason: %reason%!'
  LoginIPBan: 'Your IP is banned!'
  warnMsgVictim: '&7You have been warned by &3%admin%&7. Reason: &4%reason%!'
  warnMsgBroadcast: '&4%victim% &7was warned by &3%admin%&7. Reason: &4%reason%!'
  tempipbanMsgVictim: 'You have been temp. ipbanned by %admin%. Reason: %reason%!'
  tempipbanMsgBroadcast: '&4%victim% &7was temp. ipbanned by &3%admin%&7. Reason: &4%reason%!'
